name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install bazel
        working-directory: /tmp
        run: |
          curl -LO https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel-0.29.1-installer-linux-x86_64.sh
          chmod +x bazel-0.29.1-installer-linux-x86_64.sh
          ./bazel-0.29.1-installer-linux-x86_64.sh --user
      - name: Build
        env:
          BAZEL_CMD_ARGS: --sandbox_debug --jobs=2 --local_ram_resources=HOST_RAM*.5
        run: PATH=${PATH}:${HOME}/bin make release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bazel-bin/bazel_ipfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
